"""
ai-session-manager CLI — manage wrapper-based session persistence for AI CLIs.

Commands:
  setup     Rename the real tool binary to <tool>-real and install wrappers.
  teardown  Restore original tool binaries.
  status    Show installation state for supported tools.
  reset     Delete persisted wrapper state for supported tools.
"""

from __future__ import annotations

import argparse
import platform
import shutil
import stat
import sys
import textwrap
from pathlib import Path

from ai_session_manager.wrapper import (
    LEGACY_FOLDER_SESSION_FILE,
    LEGACY_REPO_SESSION_FILE,
    TOOLS,
    ToolSpec,
    _legacy_copilot_session_file,
    _legacy_repo_state_file,
    _state_file,
)


IS_WINDOWS = platform.system() == "Windows"
ALL_TOOLS = tuple(sorted(TOOLS))
TOOL_CHOICES = (*ALL_TOOLS, "all")

_UNIX_WRAPPER = textwrap.dedent(
    """\
    #!/usr/bin/env python3
    # Auto-generated by ai-session-manager setup
    from ai_session_manager.wrapper import run
    run({tool_key!r})
    """
)

_WINDOWS_CMD_WRAPPER = textwrap.dedent(
    """\
    @echo off
    set "AI_SESSION_MANAGER_REAL_BIN=%~dp0{real_name}"
    set "AI_SESSION_MANAGER_TOOL={tool_key}"
    python -c "from ai_session_manager.wrapper import run; run()" %*
    """
)


def _find_binary(name: str) -> Path | None:
    found = shutil.which(name)
    return Path(found) if found else None


def _absolute_path(path: Path) -> Path:
    """Return an absolute path without resolving symlink targets."""
    return path if path.is_absolute() else Path.cwd() / path


def _real_bin_path(tool: ToolSpec, binary_path: Path) -> Path:
    """Return the path where the real binary is stored alongside the wrapper."""
    if IS_WINDOWS:
        return binary_path.parent / (binary_path.stem + "-real" + binary_path.suffix)
    return binary_path.parent / f"{tool.binary_name}-real"


def _wrapper_path(binary_path: Path) -> Path:
    """Return the path of the wrapper file to install."""
    if IS_WINDOWS:
        return binary_path.parent / (binary_path.stem + ".cmd")
    return binary_path


def _real_bin_candidates(tool: ToolSpec, anchor_path: Path) -> list[Path]:
    """Return possible real binary paths next to anchor_path."""
    parent = anchor_path.parent
    stem = f"{tool.binary_name}-real"
    candidates: list[Path] = []
    seen: set[Path] = set()

    suffixes = [anchor_path.suffix]
    if IS_WINDOWS:
        suffixes.extend([".exe", ".cmd", ".bat", ".com", ""])
    else:
        suffixes.append("")

    for suffix in suffixes:
        candidate = parent / f"{stem}{suffix}"
        if candidate in seen:
            continue
        seen.add(candidate)
        candidates.append(candidate)

    return candidates


def _resolve_real_binary_for_teardown(tool: ToolSpec, binary_path: Path, fallback_real: Path | None) -> Path | None:
    """Resolve the real binary path when removing wrappers."""
    if binary_path.name.startswith(f"{tool.binary_name}-real"):
        return binary_path

    preferred = _real_bin_path(tool, binary_path)
    if preferred.exists():
        return preferred

    for candidate in _real_bin_candidates(tool, binary_path):
        if candidate.exists():
            return candidate

    if fallback_real is not None and fallback_real.exists():
        return fallback_real.resolve()

    return None


def _restored_binary_path(tool: ToolSpec, binary_path: Path, real_bin: Path) -> Path:
    """Return where the restored binary should be moved."""
    if binary_path.name.startswith(f"{tool.binary_name}-real"):
        return binary_path.with_name(f"{tool.binary_name}{binary_path.suffix}")
    return real_bin.with_name(f"{tool.binary_name}{real_bin.suffix}")


def _is_wrapper(path: Path) -> bool:
    """Return True if the file at path is our wrapper."""
    try:
        contents = path.read_text(errors="replace")
    except OSError:
        return False
    return "ai_session_manager.wrapper" in contents


def _write_wrapper(tool: ToolSpec, wrapper_path: Path, real_bin: Path) -> None:
    if IS_WINDOWS:
        wrapper_path.write_text(
            _WINDOWS_CMD_WRAPPER.format(real_name=real_bin.name, tool_key=tool.key)
        )
        return

    wrapper_path.write_text(_UNIX_WRAPPER.format(tool_key=tool.key))
    wrapper_path.chmod(real_bin.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)


def _resolve_tools(requested: list[str]) -> list[ToolSpec]:
    if not requested or "all" in requested:
        return [TOOLS[name] for name in ALL_TOOLS]
    return [TOOLS[name] for name in requested]


def _tool_header(tool: ToolSpec) -> None:
    print(f"[{tool.binary_name}]")


def cmd_setup(args: argparse.Namespace) -> int:
    explicit = bool(args.tools and "all" not in args.tools)
    exit_code = 0
    processed = 0

    for tool in _resolve_tools(args.tools):
        _tool_header(tool)
        binary_path = _find_binary(tool.binary_name)
        if binary_path is None:
            print(f"Skipping: '{tool.binary_name}' not found in PATH.")
            if explicit:
                exit_code = 1
            continue

        processed += 1
        binary_path = _absolute_path(binary_path)
        real_bin = _real_bin_path(tool, binary_path)
        wrapper = _wrapper_path(binary_path)
        wrapper_active = _is_wrapper(wrapper)

        if wrapper_active and real_bin.exists():
            print(f"Already set up: real binary is {real_bin}")
            print(f"Wrapper is at:  {wrapper}")
            continue

        if not wrapper_active and real_bin.exists():
            print(f"Detected {tool.binary_name} was reinstalled — updating {real_bin.name}.")
            binary_path.replace(real_bin)
        elif not wrapper_active:
            binary_path.rename(real_bin)
            print(f"Renamed {binary_path.name} -> {real_bin.name}")

        _write_wrapper(tool, wrapper, real_bin)
        print(f"Wrapper installed at {wrapper}")

    if processed == 0:
        print("No supported tool binaries were found.")
        return 1
    return exit_code


def cmd_teardown(args: argparse.Namespace) -> int:
    explicit = bool(args.tools and "all" not in args.tools)
    exit_code = 0
    processed = 0

    for tool in _resolve_tools(args.tools):
        _tool_header(tool)
        binary_path = _find_binary(tool.binary_name)
        fallback_real = _find_binary(f"{tool.binary_name}-real")
        if binary_path is None:
            if fallback_real is None:
                print(f"Skipping: neither '{tool.binary_name}' nor '{tool.binary_name}-real' found.")
                if explicit:
                    exit_code = 1
                continue
            binary_path = fallback_real

        processed += 1
        binary_path = _absolute_path(binary_path)
        real_bin = _resolve_real_binary_for_teardown(
            tool, binary_path, _absolute_path(fallback_real) if fallback_real is not None else None
        )
        if binary_path.name.startswith(f"{tool.binary_name}-real"):
            wrapper = _wrapper_path(binary_path.with_name(f"{tool.binary_name}{binary_path.suffix}"))
        else:
            wrapper = _wrapper_path(binary_path)

        if real_bin is None or not real_bin.exists():
            print("Nothing to undo: real binary not found alongside wrapper.")
            continue

        restored_binary = _restored_binary_path(tool, binary_path, real_bin)
        wrapper.unlink(missing_ok=True)
        real_bin.rename(restored_binary)
        print(f"Restored {real_bin.name} -> {restored_binary.name}")

    if processed == 0:
        print("No supported tool binaries were found.")
        return 1
    return exit_code


def cmd_status(args: argparse.Namespace) -> int:
    for index, tool in enumerate(_resolve_tools(args.tools)):
        if index:
            print()

        binary_path = _find_binary(tool.binary_name)
        real_bin = _find_binary(f"{tool.binary_name}-real")
        _, state_path, _ = _state_file(tool.key)

        print(f"Tool         : {tool.binary_name}")
        print(f"Platform     : {platform.system()}")
        print(f"Binary       : {binary_path or 'not found'}")
        print(f"Real binary  : {real_bin or 'not found'}")
        print(f"State file   : {state_path}")
        print(f"State        : {'present' if state_path.exists() else 'missing'}")

        if binary_path:
            wrapper = _wrapper_path(binary_path.resolve())
            if _is_wrapper(wrapper):
                print("Status       : wrapper active")
            else:
                print("Status       : real binary")
        else:
            print("Status       : not installed")

    return 0


def cmd_reset(args: argparse.Namespace) -> int:
    for tool in _resolve_tools(args.tools):
        _tool_header(tool)
        scope_dir, state_path, scope_kind = _state_file(tool.key)
        removed_paths: list[Path] = []

        if state_path.exists():
            state_path.unlink()
            removed_paths.append(state_path)

        legacy_repo_state_path = _legacy_repo_state_file(tool.key)
        if legacy_repo_state_path is not None and legacy_repo_state_path.exists():
            legacy_repo_state_path.unlink()
            removed_paths.append(legacy_repo_state_path)

        if tool.key == "copilot":
            legacy_path = _legacy_copilot_session_file()
            if legacy_path.exists():
                legacy_path.unlink()
                removed_paths.append(legacy_path)

        if removed_paths:
            for removed_path in removed_paths:
                print(f"Removed: {removed_path}")
            print(f"Next '{tool.binary_name}' in this {scope_kind} will start fresh.")
        else:
            legacy_hint = ""
            if legacy_repo_state_path is not None:
                legacy_hint = f" or migrated legacy {legacy_repo_state_path.name}"
            if tool.key == "copilot":
                legacy_name = LEGACY_REPO_SESSION_FILE if scope_kind == "repo" else LEGACY_FOLDER_SESSION_FILE
                legacy_hint = f"{legacy_hint} or legacy {legacy_name}"
            print(f"No state file found for this {scope_kind}: {scope_dir}{legacy_hint}")

    return 0

def main() -> None:
    parser = argparse.ArgumentParser(
        prog="ai-session-manager",
        description="Manage per-project session persistence for AI CLI tools.",
    )
    sub = parser.add_subparsers(dest="command", metavar="COMMAND")

    for name, help_text in (
        ("setup", "Install wrappers for supported tools"),
        ("teardown", "Remove wrappers and restore original binaries"),
        ("status", "Show current installation state"),
        ("reset", "Delete persisted wrapper state"),
    ):
        subparser = sub.add_parser(name, help=help_text)
        subparser.add_argument("tools", nargs="*", choices=TOOL_CHOICES, help="Tools to target")

    args = parser.parse_args()

    dispatch = {
        "setup": cmd_setup,
        "teardown": cmd_teardown,
        "status": cmd_status,
        "reset": cmd_reset,
    }

    if args.command not in dispatch:
        parser.print_help()
        sys.exit(0)

    sys.exit(dispatch[args.command](args))


if __name__ == "__main__":
    main()
