"""
copilot-session CLI — manage the Copilot session-persistence wrapper.

Commands:
  setup     Rename the real copilot binary to copilot-real and install the wrapper.
  teardown  Restore the original copilot binary.
  status    Show current installation state.
  reset     Delete the session file for the current git repo or folder.
"""

from __future__ import annotations

import argparse
import platform
import shutil
import stat
import sys
import textwrap
from pathlib import Path

from copilot_session.wrapper import _session_target


IS_WINDOWS = platform.system() == "Windows"

# Unix wrapper: a tiny Python shebang script
_UNIX_WRAPPER = textwrap.dedent("""\
    #!/usr/bin/env python3
    # Auto-generated by copilot-session setup
    from copilot_session.wrapper import run
    run()
""")

# Windows wrapper: a .cmd file that sets COPILOT_REAL_BIN and delegates to Python
_WINDOWS_CMD_WRAPPER = textwrap.dedent("""\
    @echo off
    set "COPILOT_REAL_BIN=%~dp0{real_name}"
    python -c "from copilot_session.wrapper import run; run()" %*
""")


def _find_binary(name: str) -> Path | None:
    found = shutil.which(name)
    return Path(found) if found else None


def _real_bin_path(copilot_bin: Path) -> Path:
    """Return the path where we will store the real binary alongside the wrapper."""
    if IS_WINDOWS:
        return copilot_bin.parent / (copilot_bin.stem + "-real" + copilot_bin.suffix)
    return copilot_bin.parent / "copilot-real"


def _wrapper_path(copilot_bin: Path) -> Path:
    """Return the path of the wrapper file to install."""
    if IS_WINDOWS:
        # Install a .cmd wrapper alongside copilot.exe
        return copilot_bin.parent / (copilot_bin.stem + ".cmd")
    return copilot_bin


def _is_wrapper(path: Path) -> bool:
    """Return True if the file at path is our wrapper."""
    try:
        return "copilot_session.wrapper" in path.read_text(errors="replace")
    except OSError:
        return False


def _write_wrapper(wrapper_path: Path, real_bin: Path) -> None:
    if IS_WINDOWS:
        wrapper_path.write_text(_WINDOWS_CMD_WRAPPER.format(real_name=real_bin.name))
    else:
        wrapper_path.write_text(_UNIX_WRAPPER)
        wrapper_path.chmod(
            real_bin.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH
        )


def cmd_setup(args: argparse.Namespace) -> int:
    copilot_bin = _find_binary("copilot")

    if copilot_bin is None:
        print("ERROR: 'copilot' not found in PATH.", file=sys.stderr)
        return 1

    copilot_bin = copilot_bin.resolve()
    real_bin = _real_bin_path(copilot_bin)
    wrapper = _wrapper_path(copilot_bin)

    wrapper_active = _is_wrapper(wrapper)

    if wrapper_active and real_bin.exists():
        print(f"Already set up: real binary is {real_bin}")
        print(f"Wrapper is at:  {wrapper}")
        return 0

    if not wrapper_active and real_bin.exists():
        # copilot was reinstalled/updated externally — promote new binary to copilot-real.
        print(f"Detected copilot was reinstalled — updating {real_bin.name} with new binary.")
        copilot_bin.replace(real_bin)
    elif not wrapper_active:
        # First time setup: rename the real binary.
        copilot_bin.rename(real_bin)
        print(f"Renamed {copilot_bin.name} → {real_bin.name}")

    _write_wrapper(wrapper, real_bin)
    print(f"Wrapper installed at {wrapper}")
    print("Done. Run 'copilot-session status' to verify.")
    return 0


def cmd_teardown(args: argparse.Namespace) -> int:
    copilot_bin = _find_binary("copilot")

    if copilot_bin is None:
        print("ERROR: 'copilot' not found in PATH.", file=sys.stderr)
        return 1

    copilot_bin = copilot_bin.resolve()
    real_bin = _real_bin_path(copilot_bin)
    wrapper = _wrapper_path(copilot_bin)

    if not real_bin.exists():
        print("Nothing to undo: real binary not found alongside wrapper.")
        return 0

    wrapper.unlink(missing_ok=True)
    real_bin.rename(copilot_bin)
    print(f"Restored {real_bin.name} → {copilot_bin.name}")
    print("Teardown complete.")
    return 0


def cmd_status(args: argparse.Namespace) -> int:
    copilot_bin = _find_binary("copilot")
    real_names = ["copilot-real.exe", "copilot-real"] if IS_WINDOWS else ["copilot-real"]
    real_bin = next((_find_binary(n) for n in real_names if _find_binary(n)), None)

    print(f"Platform     : {platform.system()}")
    print(f"copilot      : {copilot_bin or 'not found'}")
    print(f"copilot-real : {real_bin or 'not found'}")

    if copilot_bin:
        wrapper = _wrapper_path(copilot_bin.resolve())
        if _is_wrapper(wrapper):
            print("Status       : wrapper active ✓")
        else:
            print("Status       : real binary (wrapper NOT installed)")
    return 0


def cmd_reset(args: argparse.Namespace) -> int:
    scope_dir, session_file, scope_kind = _session_target()

    if session_file.exists():
        session_file.unlink()
        print(f"Session file removed: {session_file}")
        print(f"Next 'copilot' in this {scope_kind} will start a fresh session.")
    else:
        print(f"No session file found for this {scope_kind}: {scope_dir}")
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(
        prog="copilot-session",
        description="Manage per-repo and per-folder session persistence for GitHub Copilot CLI.",
    )
    sub = parser.add_subparsers(dest="command", metavar="COMMAND")

    sub.add_parser("setup",    help="Install the copilot wrapper")
    sub.add_parser("teardown", help="Remove the wrapper and restore the original binary")
    sub.add_parser("status",   help="Show current installation state")
    sub.add_parser("reset",    help="Delete the session file for the current git repo or folder")

    args = parser.parse_args()

    dispatch = {
        "setup":    cmd_setup,
        "teardown": cmd_teardown,
        "status":   cmd_status,
        "reset":    cmd_reset,
    }

    if args.command not in dispatch:
        parser.print_help()
        sys.exit(0)

    sys.exit(dispatch[args.command](args))
